# 网关Http服务器配置
[HTTPWEBSERVER]
address = "0.0.0.0"
port = 8080
body-limit = "100K"
version-header = "X-Version"
#tls-cret-file = ""
#tls-key-file = ""
request-log-enable = true
#feature-cors-enable = false
feature-debug-enable = true
feature-echo-enable = true
debug-auth-username = "yongjia.chen"
debug-auth-password = "yongjiapro"

# ENDPOINTREGISTRY: 网关端点注册中心
[ENDPOINTREGISTRY]
endpoint-path = "/flux-endpoint"
service-path = "/flux-service"
# 元数据注册中心协议：默认zookeeper，可选[default,zookeeper]
registry-proto = "zookeeper"
# 启用的注册中心，默认default；其ID为下面多注册中心的key（不区分大小写）
registry-active = ["default","tencent-cloud"]
# 支持多注册中心
[ENDPOINTREGISTRY.default]
address = "${zookeeper.address}"
timeout = "${zookeeper.timeout:5s}"
[ENDPOINTREGISTRY.tencent-cloud]
address = "${tx.zookeeper.address}"
[ENDPOINTREGISTRY.huawei-cloud]
address = "${hw.zookeeper.address}"

# Dubbo BACKEND 配置参数
[BACKEND.DUBBO]
# 集群策略：[Failover, Failfast, Failsafe/Failback, Available, Broadcast, Forking]
cluster = "failover"
# 负载策略: [Random, RoundRobin, LeastActive, ConsistentHash]
load-balance = "random"
# 日志开关；如果开启则打印Dubbo调用细节
trace-enable = false
# DuoobReference 初始化等待延时
reference-delay = "30ms"
# Dubbo注册中心列表
[BACKEND.DUBBO.REGISTRY]
id = "default"
protocol = "zookeeper"
timeout = "3s"
address = "zookeeper.ifcode.net:2181"
username = ""
password = ""

# Http BACKEND 配置参数
[BACKEND.HTTP]
timeout = "10s"
# 日志开关；如果开启则打印Dubbo调用细节
trace-enable = false
